import re
import sys

def modify_file():
    try:
        with open('index.html', 'r', encoding='utf-8') as f:
            content = f.read()

        # 1. Add renderProfileView to navigate
        if "if (view === 'profile') this.renderProfileView();" not in content:
            content = content.replace(
                "if (view === 'players') this.renderPlayers();",
                "if (view === 'players') this.renderPlayers();\n                if (view === 'profile') this.renderProfileView();"
            )

        # 2. Add renderProfileView function just before showPlayer
        render_profile_code = """
            renderProfileView() {
                // Generate a select dropdown of all players
                let html = `
                    <div class="page-header" style="margin-bottom: 20px;">
                        <h2>Player Profiles</h2>
                        <p>Select a player to view their detailed performance statistics</p>
                        <select id="profile-selector" class="form-control" style="max-width: 300px; margin-top: 15px; font-size: 1.1rem; padding: 10px;" onchange="if(this.value) App.showPlayer(this.value)">
                            <option value="">-- Select a Player --</option>
                            ${this.stats.players.sort((a,b) => a.name.localeCompare(b.name)).map(p => `<option value="${p.name}">${p.name}</option>`).join('')}
                        </select>
                    </div>
                    <div id="profile-content"></div>
                `;
                document.getElementById('view-profile').innerHTML = html;
                
                // If there are players, we could auto-select the first one, or leave it empty.
                // Leaving it empty is fine.
            },
"""
        if "renderProfileView() {" not in content:
            content = content.replace("showPlayer(name) {", render_profile_code + "\n            showPlayer(name) {")

        # 3. Update showPlayer(name) with new stats
        # We'll locate the strategy breakdown section
        target = "let mostUsedStrategy = { name: 'None', runs: 0 };"
        replacement = """let mostUsedStrategy = { name: 'None', runs: 0 };
                let leastUsedStrategy = { name: 'None', runs: 999999 };
                const finishCounts = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, '6+': 0 };
                let worstFinishOverall = 0;
                
                const trackStats = {};
                p.history.forEach(h => {
                    if (h.pos >= 1 && h.pos <= 5) finishCounts[h.pos]++;
                    else finishCounts['6+']++;
                    
                    if (h.pos > worstFinishOverall) worstFinishOverall = h.pos;
                    
                    if (!trackStats[h.race]) trackStats[h.race] = { runs: 0, wins: 0, sumPos: 0 };
                    trackStats[h.race].runs++;
                    trackStats[h.race].sumPos += h.pos;
                    if (h.pos === 1) trackStats[h.race].wins++;
                });
                
                let bestTrack = { name: 'None', wins: 0, runs: 0, avg: 99 };
                Object.entries(trackStats).forEach(([name, data]) => {
                    let avg = data.sumPos / data.runs;
                    if (data.wins > bestTrack.wins || (data.wins === bestTrack.wins && avg < bestTrack.avg)) {
                        bestTrack = { name, wins: data.wins, runs: data.runs, avg };
                    }
                });"""
        
        content = content.replace(target, replacement)
        
        # 4. Also modify Object.entries(stratStats) loop to calculate least used strategy
        target2 = """if (data.runs > mostUsedStrategy.runs) {
                        mostUsedStrategy = { name, runs: data.runs };
                    }"""
        replacement2 = """if (data.runs > mostUsedStrategy.runs) {
                        mostUsedStrategy = { name, runs: data.runs };
                    }
                    if (data.runs > 0 && data.runs < leastUsedStrategy.runs) {
                        leastUsedStrategy = { name, runs: data.runs };
                    }"""
        content = content.replace(target2, replacement2)
        
        # 5. Fix leastUsedStrategy default if none
        target3 = """});

                let html = `"""
        replacement3 = """});
                if (leastUsedStrategy.runs === 999999) leastUsedStrategy = { name: 'None', runs: 0 };

                let html = `"""
        content = content.replace(target3, replacement3)

        # 6. Inject the new stats into the HTML generated by showPlayer
        # Replace the Performance Metrics grid
        old_grid = """<div class="grid-2">
                                <div class="stat-block"><div class="val" style="color:var(--gold)">${p.w}</div><div class="lbl">Wins</div></div>
                                <div class="stat-block"><div class="val" style="color:var(--silver)">${p.secondPlaces}</div><div class="lbl">2nd Places</div></div>
                                <div class="stat-block"><div class="val" style="color:var(--bronze)">${p.thirdPlaces}</div><div class="lbl">Third Places</div></div>
                                <div class="stat-block"><div class="val">${p.podiums}</div><div class="lbl">Total Podiums</div></div>
                                <div class="stat-block"><div class="val">${p.winRate}%</div><div class="lbl">Win Rate</div></div>
                                <div class="stat-block"><div class="val">${p.top3Rate}%</div><div class="lbl">Podium Rate</div></div>
                                <div class="stat-block"><div class="val">${p.top5Rate}%</div><div class="lbl">Top 5 Rate</div></div>
                                <div class="stat-block"><div class="val">${p.avgFinish}</div><div class="lbl">Avg Finish</div></div>
                            </div>"""
                            
        new_grid = """<div class="grid-2">
                                <div class="stat-block"><div class="val" style="color:var(--gold)">${p.w}</div><div class="lbl">Wins (1st)</div></div>
                                <div class="stat-block"><div class="val" style="color:var(--silver)">${p.secondPlaces}</div><div class="lbl">2nd Places</div></div>
                                <div class="stat-block"><div class="val" style="color:var(--bronze)">${p.thirdPlaces}</div><div class="lbl">3rd Places</div></div>
                                <div class="stat-block"><div class="val">${finishCounts[4]}</div><div class="lbl">4th Places</div></div>
                                <div class="stat-block"><div class="val">${finishCounts[5]}</div><div class="lbl">5th Places</div></div>
                                <div class="stat-block"><div class="val">${finishCounts['6+']}</div><div class="lbl">6th+ Places</div></div>
                                <div class="stat-block"><div class="val">${p.winRate}%</div><div class="lbl">Win Rate</div></div>
                                <div class="stat-block"><div class="val">${worstFinishOverall}</div><div class="lbl">Worst Finish</div></div>
                                <div class="stat-block" style="grid-column: span 2;"><div class="val" style="font-size: 1.2rem;">${bestTrack.name !== 'None' ? bestTrack.name : 'N/A'}</div><div class="lbl">Best Track (${bestTrack.wins}W)</div></div>
                            </div>"""
        content = content.replace(old_grid, new_grid)

        # 7. Add least used strategy to Running Style Stats
        old_strategy = """<div>Most Used: <strong>${mostUsedStrategy.name !== 'None' ? `${mostUsedStrategy.name} (${mostUsedStrategy.runs}R)` : 'N/A'}</strong></div>"""
        new_strategy = """<div>Most Used: <strong>${mostUsedStrategy.name !== 'None' ? `${mostUsedStrategy.name} (${mostUsedStrategy.runs}R)` : 'N/A'}</strong></div>
                                <div>Least Used: <strong>${leastUsedStrategy.name !== 'None' ? `${leastUsedStrategy.name} (${leastUsedStrategy.runs}R)` : 'N/A'}</strong></div>"""
        content = content.replace(old_strategy, new_strategy)

        # 8. Ensure `view-profile` HTML doesn't just contain a "Back" button anymore because renderProfileView will overwrite it entirely.
        # But wait, if someone navigates directly via another button calling `showPlayer`, it injects into `profile-content`. We should ensure `view-profile` has `profile-content`. 
        # `renderProfileView()` already resets `view-profile`'s innerHTML, so that's fine.

        # 9. One detail: `document.getElementById('profile-content').innerHTML = html;` inside `showPlayer`
        # If `profile-content` is not found, we should create it.
        # It is found because `renderProfileView` creates it, OR the original HTML has it.
        # BUT if `showPlayer` is called from clicking a card on the dashboard, it currently doesn't call `renderProfileView` first, it just does `document.getElementById('profile-content').innerHTML = ...` then `this.navigate('profile')`.
        # So we should modify `showPlayer` to first ensure the selector HTML is present if it's missing!
        
        # Let's fix that. In showPlayer:
        ensure_profile_layout = """
                if (!document.getElementById('profile-selector')) {
                    let layoutHtml = `
                        <div class="page-header" style="margin-bottom: 20px;">
                            <h2>Player Profiles</h2>
                            <p>Select a player to view their detailed performance statistics</p>
                            <select id="profile-selector" class="form-control" style="max-width: 300px; margin-top: 15px; font-size: 1.1rem; padding: 10px;" onchange="if(this.value) App.showPlayer(this.value)">
                                <option value="">-- Select a Player --</option>
                                ${this.stats.players.sort((a,b) => a.name.localeCompare(b.name)).map(pl => `<option value="${pl.name}">${pl.name}</option>`).join('')}
                            </select>
                        </div>
                        <div id="profile-content"></div>
                    `;
                    document.getElementById('view-profile').innerHTML = layoutHtml;
                }
                document.getElementById('profile-selector').value = name;
        """
        content = content.replace("document.getElementById('profile-content').innerHTML = html;",
                                  "document.getElementById('profile-content').innerHTML = html;\n" + ensure_profile_layout)

        with open('index.html', 'w', encoding='utf-8') as f:
            f.write(content)
        
        print("Successfully applied player profile enhancements.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == '__main__':
    modify_file()
